/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CalendarIntegrationCreateNestedManyWithoutUsersInput } from "./CalendarIntegrationCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { MeetingCreateNestedManyWithoutUsersInput } from "./MeetingCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { TeamMemberCreateNestedManyWithoutUsersInput } from "./TeamMemberCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CalendarIntegrationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CalendarIntegrationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CalendarIntegrationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  calendarIntegrations?: CalendarIntegrationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MeetingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MeetingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MeetingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  meetings?: MeetingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => TeamMemberCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TeamMemberCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TeamMemberCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  teamMembers?: TeamMemberCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
