/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CalendarIntegrationService } from "../calendarIntegration.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CalendarIntegrationCreateInput } from "./CalendarIntegrationCreateInput";
import { CalendarIntegration } from "./CalendarIntegration";
import { CalendarIntegrationFindManyArgs } from "./CalendarIntegrationFindManyArgs";
import { CalendarIntegrationWhereUniqueInput } from "./CalendarIntegrationWhereUniqueInput";
import { CalendarIntegrationUpdateInput } from "./CalendarIntegrationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CalendarIntegrationControllerBase {
  constructor(
    protected readonly service: CalendarIntegrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CalendarIntegration })
  @nestAccessControl.UseRoles({
    resource: "CalendarIntegration",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCalendarIntegration(
    @common.Body() data: CalendarIntegrationCreateInput
  ): Promise<CalendarIntegration> {
    return await this.service.createCalendarIntegration({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        accessToken: true,
        createdAt: true,
        id: true,
        provider: true,
        refreshToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CalendarIntegration] })
  @ApiNestedQuery(CalendarIntegrationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CalendarIntegration",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async calendarIntegrations(
    @common.Req() request: Request
  ): Promise<CalendarIntegration[]> {
    const args = plainToClass(CalendarIntegrationFindManyArgs, request.query);
    return this.service.calendarIntegrations({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        id: true,
        provider: true,
        refreshToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CalendarIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarIntegration",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async calendarIntegration(
    @common.Param() params: CalendarIntegrationWhereUniqueInput
  ): Promise<CalendarIntegration | null> {
    const result = await this.service.calendarIntegration({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        id: true,
        provider: true,
        refreshToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CalendarIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarIntegration",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCalendarIntegration(
    @common.Param() params: CalendarIntegrationWhereUniqueInput,
    @common.Body() data: CalendarIntegrationUpdateInput
  ): Promise<CalendarIntegration | null> {
    try {
      return await this.service.updateCalendarIntegration({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          accessToken: true,
          createdAt: true,
          id: true,
          provider: true,
          refreshToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CalendarIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarIntegration",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCalendarIntegration(
    @common.Param() params: CalendarIntegrationWhereUniqueInput
  ): Promise<CalendarIntegration | null> {
    try {
      return await this.service.deleteCalendarIntegration({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          id: true,
          provider: true,
          refreshToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
